import { describe, expect, test } from "vitest";

import * as core from "../src/index.js";

describe("public API surface", () => {
  test("exports only the documented CLI-facing runtime API", () => {
    expect(Object.keys(core).sort()).toEqual([
      "addBundleItem",
      "addFormulaPackage",
      "addLocalPackage",
      "addRegistry",
      "atomicWriteJson",
      "atomicWriteText",
      "cloneOrFetchRegistry",
      "createBundle",
      "discoverMcpServersFromWeb",
      "ensureDefaultRegistry",
      "generateFormulaDraft",
      "getBundle",
      "getCapability",
      "getRegistry",
      "hasPackage",
      "ingestAgentScanFindings",
      "linkBundle",
      "listBundles",
      "listCapabilities",
      "listPackages",
      "listRegistries",
      "loadBuiltinConfigRegistry",
      "parseRegistryUrl",
      "planBundleLink",
      "previewFormulaPackageUpdate",
      "readCapabilityIndex",
      "readFormula",
      "readLinkRecords",
      "readMcpDiscoveryDocument",
      "readSamxLock",
      "removeBundle",
      "removeBundleItem",
      "removeFormulaPackage",
      "removeLocalPackage",
      "removeRegistry",
      "renderAnalyzeJsonReport",
      "renderAnalyzeMarkdownReport",
      "renderAnalyzeTerminalReport",
      "resolveBundleItem",
      "runAnalyze",
      "runBundleCheck",
      "samxPaths",
      "scanForExtensionFiles",
      "searchFormulas",
      "trustRegistry",
      "unlinkBundle",
      "updateFormulaPackage",
      "validateFormulaFiles",
      "validateStoreId",
      "writeMcpDiscoveryFormulas",
    ]);
  });
});
